apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlops-inference.fullname" . }}-config
  labels:
    {{- include "mlops-inference.labels" . | nindent 4 }}
data:
  MODEL_RUN_ID: {{ .Values.config.modelRunId | quote }}
