apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlops-inference.fullname" . }}
  labels:
    {{- include "mlops-inference.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mlops-inference.selectorLabels" . | nindent 4 }}
